name: Build & Test

# Check for PR's to main.
on:
  pull_request:
    branches: [ "main" ]

# Only allow read acces for token.
permissions:
  contents: read

jobs:
  main:
    name: Main
    # This will already have python installed.
    runs-on: ${{ matrix.os }}

    # Strategy for this job.
    strategy:
      # Continue testing on other OSes even if one fails.
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      # Checkout git repo.
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          # Caching pip may help to speed up reruns.
          cache: pip

      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -q src/test
